# Generated by Django 2.2.13 on 2020-06-23 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hgfjhfgf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_hgfjhfgf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hjgjfgf',
            field=models.ManyToManyField(blank=True, related_name='homepage_hjgjfgf', to=settings.AUTH_USER_MODEL),
        ),
    ]
